[tool.mypy]
check_untyped_defs = true
files = ["AISnake"] # Настройка файлов для обработки mypy

[[tool.mypy.overrides]]
ignore_missing_imports = true

[tool.ruff]
src = ["AISnake"] # first-party

[tool.ruff.lint]
extend-select = [
    # "D",   # pydocstyle
    "I", # isort
    "B", # flake8-bugbear
    "S", # flake8-bandit
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S101"]
"*.py" = ["S311"]